package com.caair

class AppMail {
    long id                         // primary key (Auto generated by its own sequence)
    String recipients               // recipients email to
    String subject                  // subject of mail
    String mailBody                 // body of mail
    String mimeType                 // mime type of mail
    String recipientsCc             // recipients cc
    String displayName              // sender's name
    String emailFrom                // creator

    byte[] attachment               // byte array of attachment
    String attachmentName           // attached file name
    String attachmentMimeType       // attached file mime type - application/pdf, application/csv
}
