package com.caair.entity

/**
 * <p>
 * <strong>Module:</strong> CAAir </br>
 * <strong>Purpose:</strong> One or more entity/features perform under AirPlane.
 *
 * <p><strong>Foreign Reference:</strong> Other domain, which has foreign key reference of AirPlane:</p>
 * <ul>
 *     <li>{@link com.caair.entity.Flight#airPlaneId}</li>
 * </ul>
 */
class AirPlane {

    long id                 // primary key (Auto generated by its own sequence)
    long version            // entity version in the persistence layer
    String name             // name of air plane
    int totalSeat           // number of total seat

    static mapping = {
        id generator: 'sequence', params: [sequence: 'air_plane_id_seq']
    }

    static constraints = {
        name(blank: false, nullable: false, unique: true)
        totalSeat(nullable: false)
    }

    @Override
    public String toString() {
        return name;
    }
}
