package com.caair.entity

/**
 * <p>
 * <strong>Module:</strong> CAAir </br>
 * <strong>Purpose:</strong> One or more entity/features perform under AppUser.
 *
 * <p><strong>Foreign Reference:</strong> Other domain, which has foreign key reference of AppUser:</p>
 * <ul>
 *     <li>{@link com.caair.entity.AppUserRole#userId}</li>
 *     <li>{@link com.caair.entity.OAuthID#userId}</li>
 * </ul>
 */
class AppUser {

    long id                     // primary key (Auto generated by its own sequence)
    long version                // entity version in the persistence layer
    String username             // username
    String password             // password
    boolean enabled             // account enable flag(true/false)
    boolean accountExpired      // account expire flag(true/false)
    boolean accountLocked       // account lock flag(true/false)
    boolean passwordExpired     // password expire flag(true/false)
    String gender               // gender of user
    String imagePath            // path of user image

    static mapping = {
        password column: '`password`'
    }

    static constraints = {
        username blank: false, unique: true
        password blank: false
        imagePath(nullable: true)
    }

    Set<Role> getAuthorities() {
        List<Long> lstRoleIds = AppUserRole.findAllByUserId(this.id, [readOnly: true]).collect { it.roleId }
        Role.findAllByIdInList(lstRoleIds)
    }

    public String toString() {
        return this.username
    }
}
