package com.caair.entity

/**
 * <p>
 * <strong>Module:</strong> CAAir </br>
 * <strong>Purpose:</strong> One or more entity/features perform under Flight.
 * Flight has association with few other domains as listed below.
 * </p>
 *
 * <p><strong>Foreign Reference:</strong> Other domain, which has foreign key reference of Flight:</p>
 * <ul>
 *     <li>{@link com.caair.entity.PaymentInfo#customerId}</li>
 *     <li>{@link com.caair.entity.TicketInfo#customerId}</li>
 * </ul>
 *
 *  * <p><strong>Local Reference:</strong> Has-a relationship with other domains:</p>
 * <ul>
 *     <li>{@link com.caair.entity.AirPlane#id as airPlaneId}</li>
 * </ul>
 */
class Flight {

    long id                         // primary key (Auto generated by its own sequence)
    long version                    // entity version in the persistence layer
    long airPlaneId                 // AirPlane.id
    String departureAirPort         // departure airport name
    String arrivalAirPort           // arrival airport name
    Date departureTime              // time of departure
    Date arrivalTime                // time of arrival

    static mapping = {
        id generator: 'sequence', params: [sequence: 'flight_id_seq']
        airPlaneId index: 'flight_air_plane_id_idx'
    }

    static constraints = {
        airPlaneId(nullable: false)
        departureAirPort(nullable: false)
        arrivalAirPort(nullable: false)
        departureTime(nullable: false)
        arrivalTime(nullable: false)
    }
}
