package com.caair.entity

/**
 * <p>
 * <strong>Module:</strong> CAAir </br>
 * <strong>Purpose:</strong> One or more entity/features perform under PaymentInfo.
 * PaymentInfo has association with few other domains as listed below.
 * </p>
 *
 * <p><strong>Foreign Reference:</strong> Other domain, which has foreign key reference of PaymentInfo:</p>
 * <ul>
 *     <li>{@link com.caair.entity.TicketInfo#paymentInfoId}</li>
 * </ul>
 *
 *  * <p><strong>Local Reference:</strong> Has-a relationship with other domains:</p>
 * <ul>
 *     <li>{@link com.caair.entity.Customer#id as customerId}</li>
 * </ul>
 */
class PaymentInfo {

    long id                         // primary key (Auto generated by its own sequence)
    long version                    // entity version in the persistence layer
    long customerId                 // Customer.id
    String cardType                 // card type
    String cardNo                   // card no
    String cardExpiredDate          // card expired date
    String transactionNo            // No. of transaction
    Date transactionDate            // date of transaction
    Double price                    // price
    String paymentStatus            // status of payment

    static mapping = {
        id generator: 'sequence', params: [sequence: 'payment_info_id_seq']
        customerId index: 'payment_info_customer_id_idx'
    }

    static constraints = {
        customerId(nullable: false)
        cardType(nullable: false)
        cardNo(nullable: false)
        cardExpiredDate(nullable: false)
        transactionNo(nullable: false)
        transactionDate(nullable: false)
        price(nullable: false)
        paymentStatus(nullable: false)
    }

    @Override
    public String toString() {
        return "Transaction No : " + transactionNo + " Paid Amount : " + price;
    }
}
