package com.caair.entity

/**
 * <p>
 * <strong>Module:</strong> Application </br>
 * <strong>Purpose:</strong> Determines access control of all features.
 * </p>
 *
 */
class RequestMap {

    long id                         // primary key (Auto generated by its own sequence)
    long version                    // entity version in the persistence layer
    String configAttribute          // comma separated Role authority
    String url                      // url (e.g : '/appUser/show')

    static mapping = {
        id generator: 'sequence', params: [sequence: 'request_map_id_seq']
    }

    static constraints = {
        configAttribute blank: false
        url blank: false
    }
}