package com.caair.entity

/**
 * <p>
 * <strong>Module:</strong> CAAir </br>
 * <strong>Purpose:</strong> One or more entity/features perform under TicketInfo.
 * TicketInfo has association with few other domains as listed below.
 * </p>
 *
 *
 * <p><strong>Local Reference:</strong> Has-a relationship with other domains:</p>
 * <ul>
 *     <li>{@link com.caair.entity.Customer#id as customerId}</li>
 *     <li>{@link com.caair.entity.Flight#id as flightId}</li>
 *     <li>{@link com.caair.entity.PaymentInfo#id as paymentInfoId}</li>
 * </ul>
 */
class TicketInfo {

    long id                     // primary key (Auto generated by its own sequence)
    long version                // entity version in the persistence layer
    long customerId             // Customer.id
    long flightId               // Flight.id
    long paymentInfoId          // PaymentInfo.id
    boolean isBooked            // true/false, default value is false, if booked then true
    boolean isPaid              // true/false default value is false, if paid then true
    Double price                // price
    String ticketNo             // No. of ticket

    static mapping = {
        id generator: 'sequence', params: [sequence: 'ticket_info_id_seq']
        customerId index: 'ticket_info_customer_id_idx'
        flightId index: 'ticket_info_flight_id_idx'
        paymentInfoId index: 'ticket_info_payment_info_id_idx'
    }

    static constraints = {
        customerId(nullable: false)
        flightId(nullable: false)
        paymentInfoId(nullable: true)
        price(nullable: false)
        ticketNo(nullable: true)
    }
}
